version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/redis_data

  pygeoapi_server:
    image: geopython/pygeoapi:latest
    volumes:
      - ./provider/earthquake_rasterio_.py:/pygeoapi/pygeoapi/provider/earthquake_rasterio_.py
      - ./plugin.py:/pygeoapi/pygeoapi/plugin.py
      - ./my.config.yml:/pygeoapi/local.config.yml
      - ./tests/data/earthquake/earthquake_ExpDisp.tif:/pygeoapi/tests/data/earthquake/earthquake_ExpDisp.tif
      - ./tests/data/earthquake/earthquake_GDP.tif:/pygeoapi/tests/data/earthquake/earthquake_GDP.tif
      - ./tests/data/earthquake/earthquake_hazMean1.tif:/pygeoapi/tests/data/earthquake/earthquake_hazMean1.tif
      - ./tests/data/earthquake/earthquake_hazSD1.tif:/pygeoapi/tests/data/earthquake/earthquake_hazSD1.tif
      - ./tests/data/earthquake/earthquake_HiCIDisp.tif:/pygeoapi/tests/data/earthquake/earthquake_HiCIDisp.tif
      - ./tests/data/earthquake/earthquake_LowCIDisp.tif:/pygeoapi/tests/data/earthquake/earthquake_LowCIDisp.tif
      - ./tests/data/earthquake/earthquake_Population.tif:/pygeoapi/tests/data/earthquake/earthquake_Population.tif
      - ./tests/data/earthquake/earthquake_RWI.tif:/pygeoapi/tests/data/earthquake/earthquake_RWI.tif
    ports:
      - "5000:80"
    environment:
     - SCRIPT_NAME=/pygeoapi

  server:
    build: .
    env_file:
      - .env
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - .:/code
    ports:
      - "9001:9001"
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis-data:
