server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000/pygeoapi/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: 'Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
#        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/master.log

metadata:
    identification:
        title: pygeoapi default instance
        description: pygeoapi provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/geopython/pygeoapi
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: pygeoapi Development Team
        url: https://pygeoapi.io
    contact:
        name: ToggleCorp Solutions
        position: Software Company
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Neapal
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: https://pygeoapi.io
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources:
    obs:
        type: collection
        title: Observation
        description: My Observation
        keywords:
            - observations
            - monitoring
        crs:
            - CRS84
        links:
            - type: text/csv
              rel: canonical
              title: data
              href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
            - type: text/csv
              rel: alternate
              title: Demo data
              href: https://raw.githubusercontent.com/mapserver/mapserver/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2000-10-30T18:24:39Z
                end: 2007-10-30T08:57:29Z
        providers:
            - type: feature
              name: CSV
              data: tests/data/obs.csv
              id_field: id
              geometry:
                  x_field: long
                  y_field: lat

    earthquake_exposure_displacement:
        type: collection
        title: Earthquake exposure displacement
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_ExpDisp.tif
              options:
                  DATA_ENCODING: SIMPLE_PACKING
              format:
                  name: TIF
                  mimetype: application/tif

    earthquake_gdp:
        type: collection
        title: Earthquake GDP
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_GDP.tif
              options:
                  DATA_ENCODING: SIMPLE_PACKING
              format:
                  name: TIF
                  mimetype: application/tif

    earthquake_mean:
        type: collection
        title: Earthquake Mean
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_hazMean1.tif
              options:
                DATA_ENCODING: SIMPLE_PACKING
              format:
                name: TIF
                mimetype: application/tif

    earthquake_sd:
        type: collection
        title: Earthquake SD
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_hazSD1.tif
              options:
                  DATA_ENCODING: SIMPLE_PACKING
              format:
                  name: TIF
                  mimetype: application/tif

    earthquake_hi_disp:
        type: collection
        title: Earthquake High Displacement
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_HiCIDisp.tif
              options:
                  DATA_ENCODING: SIMPLE_PACKING
              format:
                  name: TIF
                  mimetype: application/tif

    earthquake_low_disp:
        type: collection
        title: Earthquake Low Displacement
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_LowCIDisp.tif
              options:
                  DATA_ENCODING: SIMPLE_PACKING
              format:
                  name: TIF
                  mimetype: application/tif

    earthquake_population:
        type: collection
        title: Earthquake Affected Population
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_Population.tif
              options:
                  DATA_ENCODING: SIMPLE_PACKING
              format:
                  name: TIF
                  mimetype: application/tif

    earthquake_rwi:
        type: collection
        title: Earthquake RWI
        description: Earthquake in world
        keywords:
            - earthquake
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: earthquake
              data: tests/data/earthquake/earthquake_RWI.tif
              options:
                  DATA_ENCODING: SIMPLE_PACKING
              format:
                  name: TIF
                  mimetype: application/tif