# Generated by Django 3.2.7 on 2021-09-14 09:13

from django.db import migrations, models
import django_enumfield.db.fields
import earthquake.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255, verbose_name='event title')),
                ('event_place', models.CharField(max_length=255, verbose_name='event place')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='event date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('depth', models.FloatField(verbose_name='depth')),
                ('magnitude', models.FloatField(verbose_name='magnitude')),
                ('magnitude_type', django_enumfield.db.fields.EnumField(enum=earthquake.models.Earthquake.MagnitudeType)),
            ],
        ),
    ]
