# Generated by Django 3.2.8 on 2021-12-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0016_pdc_pdcdisplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdc',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('E', 'Expired')], max_length=20, verbose_name='status'),
        ),
    ]
