# Generated by Django 3.2.7 on 2021-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('country_code', models.CharField(max_length=3, verbose_name='code')),
                ('analysis_date', models.DateField(blank=True, null=True, verbose_name='analysis date')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('phase_popultion', models.IntegerField(verbose_name='phase population')),
                ('census_population', models.IntegerField(verbose_name='census population')),
                ('current_from_date', models.DateField(blank=True, null=True, verbose_name='current from date')),
                ('current_to_date', models.DateField(blank=True, null=True, verbose_name='current to date')),
                ('projected_from_date', models.DateField(blank=True, null=True, verbose_name='projected from date')),
                ('projected_to_date', models.DateField(blank=True, null=True, verbose_name='projected to date')),
            ],
        ),
    ]
