# Generated by Django 3.2.7 on 2021-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThinkHazardCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('country_code', models.CharField(max_length=7, verbose_name='country code')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
            ],
        ),
    ]
